# Generated by Django 4.2.1 on 2023-06-19 09:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0003_alter_salesorderinfo_totalamount_and_more'),
        ('Production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='production',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='production',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='production',
            name='sales_order_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sales_production_order', to='Sales.salesorderinfo'),
        ),
        migrations.AddField(
            model_name='production',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
