# Generated by Django 4.2.1 on 2023-06-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0003_production_docno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='docno',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
