# Generated by Django 4.2.2 on 2023-06-19 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0003_alter_salesorderinfo_totalamount_and_more'),
        ('Production', '0005_alter_production_docno'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReceiptNumber', models.PositiveIntegerField(default=1, unique=True)),
                ('OrderNumber', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sales.salesorderinfo')),
            ],
        ),
        migrations.AlterField(
            model_name='production',
            name='docno',
            field=models.PositiveIntegerField(default=1, unique=True),
        ),
        migrations.CreateModel(
            name='ProductionReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=50)),
                ('Quantity', models.PositiveIntegerField(default=0)),
                ('Price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('PriceTotal', models.DecimalField(decimal_places=4, max_digits=10)),
                ('ReceiptNumber', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Production.productionreceipt')),
                ('SalesOrderItem', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sales.salesorderitem')),
            ],
        ),
    ]
