# Generated by Django 4.2.2 on 2023-06-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0007_productionreceiptitem_productionno'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionreceipt',
            name='TotalAmount',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True),
        ),
    ]
