# Generated by Django 4.2.2 on 2023-06-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0008_productionreceipt_totalamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionreceiptitem',
            name='Color',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='productionreceiptitem',
            name='Size',
            field=models.CharField(default='', max_length=50),
        ),
    ]
