# Generated by Django 4.2.1 on 2023-06-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0009_productionreceiptitem_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionreceipt',
            name='OrderNumber',
        ),
        migrations.AddField(
            model_name='productionreceipt',
            name='TotalQty',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True),
        ),
    ]
