# Generated by Django 4.2.1 on 2023-06-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0010_remove_productionreceipt_ordernumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='code',
            field=models.CharField(default='', max_length=20),
        ),
    ]
