# Generated by Django 4.2.1 on 2023-06-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0011_production_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionreceiptitem',
            name='ItemCode',
            field=models.CharField(default='', max_length=50),
        ),
    ]
