# Generated by Django 4.2.1 on 2023-06-24 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0012_productionreceiptitem_itemcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billofmaterials',
            name='bomtype',
        ),
    ]
