# Generated by Django 4.2.1 on 2023-06-24 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0013_remove_billofmaterials_bomtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionreceipt',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='production',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='production',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='production',
            name='order_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='production',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
