# Generated by Django 4.2.1 on 2023-06-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderinfo',
            name='TotalAmount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
