# Generated by Django 4.2.1 on 2023-06-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0002_alter_salesorderinfo_totalamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderinfo',
            name='TotalAmount',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='PriceTotal',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
