# Generated by Django 4.2.2 on 2023-06-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0004_deliveryinfo_deliveryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinfo',
            name='SalesOrder',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
