# Generated by Django 4.2.1 on 2023-06-21 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0005_alter_deliveryinfo_salesorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryinfo',
            name='TotalQty',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesorderinfo',
            name='TotalQty',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True),
        ),
    ]
