# Generated by Django 4.2.1 on 2023-06-24 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0006_deliveryinfo_totalqty_salesorderinfo_totalqty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinfo',
            name='Created',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='salesorderinfo',
            name='Created',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
